# Generated by Django 4.2 on 2023-05-02 02:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, default='Vigente', max_length=20, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.bien')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.cliente')),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.cobertura')),
            ],
        ),
    ]
