# Generated by Django 4.2 on 2023-05-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='actualizaciones',
            field=models.IntegerField(blank=True, default=1, max_length=10, null=True),
        ),
    ]
