# Generated by Django 4.2 on 2023-05-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_poliza_estado_siniestro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='actualizaciones',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
