# Generated by Django 4.2 on 2023-05-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_poliza_actualizaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='actualizaciones',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='cuotas'),
        ),
    ]
