# Generated by Django 4.2 on 2023-05-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contacto', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formadepago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('plazo_en_dias', models.IntegerField(default=30)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.compania')),
                ('rama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.rama')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('fechaNacimiento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contacto', models.IntegerField(blank=True, null=True)),
                ('datoPago', models.CharField(max_length=255)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.formadepago')),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('chasis', models.CharField(blank=True, max_length=255, null=True)),
                ('motor', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('rama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.rama')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.cliente')),
            ],
        ),
    ]
