# Generated by Django 4.2 on 2023-05-02 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='formaPago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administracion.formadepago'),
        ),
    ]
