# Generated by Django 4.2 on 2023-05-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_cliente_formapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='ano',
            field=models.IntegerField(default=2023),
        ),
    ]
