# Generated by Django 4.2 on 2023-05-07 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_bien_ano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bien',
            options={'verbose_name': 'Bien', 'verbose_name_plural': 'Bienes'},
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='rama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administracion.rama'),
        ),
    ]
