# Generated by Django 4.2 on 2023-05-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_bien_options_alter_cobertura_rama'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
