# Generated by Django 4.2 on 2023-05-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_bien_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='fecha_de_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
