# Generated by Django 4.2 on 2023-05-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_bien_fecha_de_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='notificaciones',
            field=models.BooleanField(default=False),
        ),
    ]
