# Generated by Django 4.2 on 2023-05-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_cliente_notificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='modelo',
            field=models.CharField(default=52, max_length=255),
            preserve_default=False,
        ),
    ]
