# Generated by Django 4.2 on 2023-05-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_alter_bien_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='polizas_activas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
